In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("gpu is not available. using cpu,")

gpu is available
Using GPU: Tesla T4


##Creating a Tensor

In [3]:
# using empty
a= torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using random
torch.rand(2,3)

tensor([[0.1068, 0.5281, 0.5357],
        [0.3119, 0.5110, 0.8523]])

In [8]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# other ways of creating tensors
# arange
print("using arange ->", torch.arange(0,10,2))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))
# using eye
print("using eye ->", torch.eye(4))
# using full
print("using full ->", torch.full((2,4), 3))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
using full -> tensor([[3, 3, 3, 3],
        [3, 3, 3, 3]])


## Tensor shapes

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[                  0, 8319683848551211643, 3180222411935070754],
        [8391722768137527840, 7959390389040738153, 2318283094764429940]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor data types

In [17]:
# find data type
x.dtype

torch.int64

In [18]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
# using to()
x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical operations

## 1.Scalar operation

In [21]:
x= torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [22]:
# addition
x + 2
# subtraction
x - 2
# multiplication
x * 2
# division
x / 2
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## 2.Elememt wise operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [24]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [25]:
c = torch.tensor([2,-3,-4])

In [26]:
# abs
torch.abs(c)

tensor([2, 3, 4])

In [27]:
# negative
torch.neg(c)

tensor([-2,  3,  4])

In [28]:
d = torch.tensor([1.6, 2.3, 3.9])

In [29]:
# round
torch.round(d)

tensor([2., 2., 4.])

In [30]:
# ceil
torch.ceil(d)

tensor([2., 3., 4.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3.])

In [32]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000])

## 3.Reduction operation

In [33]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [34]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [35]:
# mean
torch.mean(e)
# mean along column
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [36]:
# median
torch.median(e)

tensor(0.)

In [37]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
# product
torch.prod(e)

tensor(0.)

In [39]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [40]:
# variance
torch.var(e)

tensor(19.6000)

In [41]:
# argmax
torch.argmax(e)

tensor(5)

In [42]:
# argmin
torch.argmin(e)

tensor(1)

## 4.Matrix operations

In [44]:
f = torch.randint(size=(2,3), low=0, high=8)
g = torch.randint(size=(3,2), low=0, high=8)
print(f)
print(g)

tensor([[1, 5, 6],
        [7, 7, 3]])
tensor([[0, 2],
        [1, 1],
        [6, 3]])


In [45]:
# matrix multiplcation
torch.matmul(f,g)

tensor([[41, 25],
        [25, 30]])

In [46]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([4,5])
# dot product
torch.dot(vector1, vector2)

tensor(14)

In [47]:
# transpose
torch.transpose(f, 0, 1)

tensor([[1, 7],
        [5, 7],
        [6, 3]])

In [48]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [49]:
# determinant
torch.det(h)

tensor(-20.0000)

In [50]:
# inverse
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

## 5.Comparison operations

In [51]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [52]:
# greater than
i > j
# lesser than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# lesser than equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

## 6.Special functions

In [53]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [54]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [55]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [57]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [58]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [59]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

## Inplace operations

In [60]:
m= torch.rand(2,3)
n= torch.rand(2,3)
print(m)
print(n)


tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [61]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [62]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [63]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [64]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [65]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [66]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

## Copying a tensor

In [68]:
a = torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [69]:
b = a

In [70]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [71]:
a[0][0] = 0

In [72]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [73]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [74]:
id(a)

133119181241904

In [75]:
id(b)

133119181241904

In [77]:
b = a.clone()

In [78]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [79]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [80]:
a[0][0] = 10

In [81]:
a

tensor([[10.0000,  0.0340,  0.9157],
        [ 0.3079,  0.6269,  0.8277]])

In [82]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [83]:
id(a)

133119181241904

In [84]:
id(b)

133118853271056